### ISSUE TITLE
iOS 6.1.3 Crash : -[LDInAppFetchDelegate respondsToSelector:]: message sent to deallocated instance

### ISSUE THREAD

**Issue by DanH-SyncInteractive** [ludei/atomic-plugins-inapps#2]
Hi,

Firstly thank you for an awesome library. However I'm having an issue with it on ios6 devices.

When I run the 'fetchProducts:completion:' call on an iTouch device running iOS 6.1.3 the app crashes. If I enable zombie objects and try again, I get the following console output:

```
*** -[LDInAppFetchDelegate respondsToSelector:]: message sent to deallocated instance 0x1f504e40
```

I noticed if in the following function below, if I comment out the CFRelease line, it prevents the crash but obviously isn't the correct solution as the memory will eventually build up as its not getting released correctly.

```
- (void)productsRequest:(SKProductsRequest *)request didReceiveResponse:(SKProductsResponse *)response
{
    NSError * error = nil;
    if (response.invalidProductIdentifiers.count > 0) {
        NSString * msg = @"Invalid products: ";
        for (NSString * pid in response.invalidProductIdentifiers) {
            msg = [msg stringByAppendingString:pid];
            msg = [msg stringByAppendingString:@","];
        }
        error = MAKE_ERROR(0, msg);
    }
    _completion(response.products, error);
    //CFRelease((__bridge CFTypeRef)(self));
}
```

I should mention this code runs fine on ios7 and above, its just on 6.1.3 I've noticed the issue. Do you know what is causing this and how I can fix it?

Many thanks

**Comment by MortimerGoro** [comment]
Hi Dan,
I have tested the demo project on an iTouch 6.1.6 and I can't reproduce the problem. Anyway, I have improved the code and made it safer. Try again with the latest version, It should fix the crash on 6.1.3

**Comment by DanH-SyncInteractive** [comment]
Hi MortimerGoro,

Thank you for looking at this issue for me so quickly.

I'll be sure to test that shortly.

But one quick question, how do I pull these latest changes via cocoa pods?

When I try

```
pod 'LDInAppService'
```
It simply installs 1.0.1 (the current version I was using).
I've tried specifying the git url to, but also haven't had luck with this as I receive an error in terminal.

```
pod 'LDInAppService', :git => 'https://github.com/ludei/atomic-plugins-inapps.git'
```

This gives me the following terminal error:
```
Pre-downloading: `LDInAppService` from `https://github.com/ludei/atomic-plugins-inapps.git`
[!] No podspec found for `LDInAppService` in /path_to_project/Pods/LDInAppService/LDInAppService.podspec.json
```

Thank you for your help so far.

**Comment by MortimerGoro** [comment]
The fix was not yet pushed to cocoapods. I have just done it. Try it now ;)

**Comment by DanH-SyncInteractive** [comment]
Thank you MortimerGoro.

I've just tested again and unfortunately the same issue is happening.

I still get the same error when I enable zombie objects.

I have two questions/suggestions...

1. Is CFAutorelease available on iOS6? I thought this was for 7.0 and above?
```
CFAutorelease((__bridge CFTypeRef)(self));
```

2. Because of the message to deallocate instance:

```
*** -[LDInAppFetchDelegate respondsToSelector:]: message sent to deallocated instance 0x1d83d030
```
Shouldn't there be some kind of retain on the LDInAppFetchDelegate?
```
LDInAppFetchDelegate * delegate = [[LDInAppFetchDelegate alloc] init];
```
I noticed in the code actually that there was the following line commented out (line 201):
```
//CFRetain((__bridge CFTypeRef)(delegate));
```
So I removed the comment to test and It gave me a different error, which was:
```
dyld: lazy symbol binding failed: Symbol not found: _CFAutorelease
  Referenced from: /var/mobile/Applications/AEA937A3-3811-4D43-B98B-D265D1D04009/test.app/test
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation

dyld: Symbol not found: _CFAutorelease
  Referenced from: /var/mobile/Applications/AEA937A3-3811-4D43-B98B-D265D1D04009/test.app/test
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
```
Which suggests back to point 1 that CFAutorelease is perhaps not available in iOS6?

Thanks again for taking the time to look at this. I think we are almost there.

**Comment by MortimerGoro** [comment]
New version available, I have simulated the missing CFAutoRelease in iOS 6.0 with a dispatch_after CFRelease. Third time's a charm ;)

**Comment by DanH-SyncInteractive** [comment]
Awesome, just tested and no crash now. Thank you so much for fixing this so quickly. Great work!
